channels:
- conda-forge
dependencies:
- python=3.11.5
- pip<=26.1.1
- pip:
  - mlflow==2.18.0
  - cloudpickle==3.1.2
  - numpy==2.4.6
  - pandas==2.3.3
  - pyarrow==18.1.0
  - scikit-learn==1.8.0
  - scipy==1.17.1
  - hyperopt==0.2.7
name: mlflow-env
